name: Build and Commit

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Build
      run: |
        go build -o main-linux cmd/api/main.go

    - name: Check out the repo again
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Configure user details
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Commit and push
      run: |
        git add myapp
        git commit -m "Add compiled binary" || echo "No changes to commit"
        git push
